apiVersion: v1
kind: Service
metadata:
  name: rfc2136-skydns-etcd-adaptor
  namespace: dns
  labels:
    app: rfc2136-skydns-etcd-adaptor
spec:
  type: ClusterIP
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: dns
  selector:
    app: rfc2136-skydns-etcd-adaptor
